language: cpp
sudo: required

services:
  - docker

matrix:
  ## fast_finish: true
  include:
    - os: linux
      env: COMPILER=g++-5
      addons:
        apt:
          packages:
          - g++-5
          ## - catch
          sources:
          - ubuntu-toolchain-r-test

before_install:
  - export CXX="${COMPILER}"
  ## https://docs.travis-ci.com/user/installing-dependencies/
  ## -qq for less output
  - sudo apt-get -qq update
  ## -y assume 'yes' as the answer
  - sudo apt-get install -y catch

  ## docker support
  #- docker pull carlad/sinatra
  #- docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  #- docker ps -a
  #s- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"  

  ## Git LFS
  ## - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  ## - git lfs pull

install:

before_script:
  # show OS/compiler version
  - uname -a
  ## - $CXX --version

script:
  # compile and execute unit tests
  - mkdir -p _build && cd _build
  - cmake .. 
  - cmake --build . --config Release -- -j4
  - ctest

after_success:
  - cpack -G DEB

before_deploy:
  ## - git fetch --tags ## TODO ehy

deploy:
  provider: releases
  api_key: 2e20b0cbe863a0da97335e9238ebff6bbc178faf
  file: "monorepo_bin1-1.0.0-Linux.deb"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true

after_deploy:

after_script:
  - echo "Deploying build $TRAVIS_BUILD_NUMBER"

notifications:
  email:
    recipients:
      - michael.miller@sofistik.de
    on_success: never     # default: change
    on_failure: always    # default: always
  irc:
    channels:
      - "chat.freenode.net#my-channel"
      - "chat.freenode.net#some-other-channel"
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
  #hipchat:
    #rooms:
#      - [api token]@[room id or name]
 #   template:
  #    - '%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
   # format: html