language: cpp
dist: trusty
sudo: enabled

matrix:
  fast_finish: true

include:
  - os: linux
    env: COMPILER=g++-5
    addons:
      apt:
        packages: ["g++-5"]
        sources: ["ubuntu-toolchain-r-test"]

before_install:
  - export CXX="${COMPILER}"
  - sudo apt-get update -qq
  - sudo apt-get install -qq "catch"

install:

before_script:
  # show OS/compiler version
  - uname -a
  ## - $CXX --version

script:
  # compile and execute unit tests
  - mkdir -p _build && cd _build
  - cmake .. 
  - cmake --build . --config Release -- -j4
  - ctest -D Experimental
  - cd ..

after_success:

before_deploy:

deploy:

after_deploy:

after_script: 