language: cpp
sudo: required
services:
- docker
matrix:
  include:
  - os: linux
    env: COMPILER=g++-5
    addons:
      apt:
        packages:
        - g++-5
        sources:
        - ubuntu-toolchain-r-test
before_install:
- export CXX="${COMPILER}"
- sudo apt-get -qq update
- sudo apt-get install -y catch
install: 
before_script:
- uname -a
script:
- mkdir -p _build && cd _build
- cmake ..
- cmake --build . --config Release -- -j4
- ctest
after_success:
- cpack -G DEB
before_deploy:
- git fetch --tags
deploy:
  provider: releases
  ## user: MichaelMiller-
  file: monorepo_bin1-1.0.0-Linux.deb
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
  ## password:
    ##secure: GnxiH5T6rHaRYe8jgVbfjV0cvTVqvxeoNyW/tr6Wbfp3681A6RH7rnGRF3wLNeVEnms0Q8crXVqKjvdwkSFL6Vjo77/YSJER3soCZljhaJJ/faP4FeiKqFKTBiGutqBt7EUm95mQ7k7+l7XCnXfuLKu5LTM6JUT/qLL2XnkUDBG5lYkydOXvV0WiEquV1ryOftd8jLuOTtQvMb3rGczbBTO4QqGEGPYst70yP77/dhm7M/3/PQFu/NCBq42kkkW0yf9YGBuktKh0K6PR8f37kqgeBF3jxV5FAPp8elW55pcybbk7RDmgkww9YcqyQ1W0JdJpCMnu9v31hbLLzKkbXWgDFGb9nh1jwk56PkApOdNZEDNCwwOzi7N96GxW33xaBo8CPBJp/fLPk1fJf33Ut/ytFvEJ7+XH4ovBuh3TkH+Uwu2Rn3w5jx93OABbX3oGwwxs+WrXWylP+H4zh5WSSzMCNnVbLTUZLqwWQHqXP7ERfURYxu4FreeSkuKBdEOSXs3wbXHT9BbzdyQ5bnUm8hu5yPsV43eX7OkNj3SQtbp2k9+csdgzlNKRI1tWSTdkQmQ6SMo6mvZStc89pHdIC6A2wm9+KthCivUq9J5VJXkCNVOUeTi0bQgP+n1c/fPJ8hVVpiYTJZNSxPWQag+AnekwWrNTSxZu49eWLTnYTdI=
  api_key:
    secure: lF0Rdo07lBNwNQqkbO5lSeMMspnxpfxZfvJvErqCW0H0qlteThW8pFhOmNc7Nex8tccr7HgFfRM9S8Q21rNKGckK7K5YI05uVwz1zFLAyNeoL/q2/G+Ofw5A8C1HM7MZkHM/MZOZQXeJaiTmF5JCOId6mVentmVPaEFQdRia2C/k7BYO20WS0FZP+6mAHJ43Csi8nt9YLP/0wKtvKDgyzz6yK/0O+dP0ugYGjZ/UAVz6xdYR2tp/sYnRBZyi2YD5R2gp8dTXq2N28ibf+ds0ly09Gikd9OWHA0ALkNGUcRsQ/HUy7iOkUbJd8yiLAq3YTLfqFYjspoletBbsIkmBp9f2R+OosLYWlyIdw1hfYPH13MYvhF4NdiJfkSAP0pg3zYyC3ds+5gNP0QyxI3vivRjpeZDBmkdPeGgiur+kwNVSOJAFKSkM0Yj/RB8qnKF2HtWHxGpjFy8ZpOjMTtTB4G4lYrbZhy6JvFi0vxc+ZMHTP1zBQ+1qIllGD8qp79wyLq1byznpbZdTWUZ6sX+uKEaVg54taEceZV+nJ0RpTwEQjvZtaZpuM2ktmisWiWokVt8zC0cFoGpyuqZ3l2xo452Q2jgE9LD9ppw3MlQkkwIbNG2BBwb719WFFRwG0BqsBqsypmaThM/RtHwrTnR3EVyihL5jGctOYb5XIjOAWiQ=
after_deploy: 
after_script:
- echo "Deploying build $TRAVIS_BUILD_NUMBER"
notifications:
  email:
    recipients:
    - michael.miller@sofistik.de
    on_success: never
    on_failure: always
  irc:
    channels:
    - chat.freenode.net#my-channel
    - chat.freenode.net#some-other-channel
    template:
    - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
